### ISSUE TITLE
Unexpected behavior (partial trees/labels appear incorrect)

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#6]
I noticed that while analyzing a set of 72 LC-MS/MS datasets of primate sera, with _E. coli_ as an "outgroup" that in the beginning of the analyses, some _E. coli_ samples were grouped with primate sera in the first trees. While the first trees may differ from the final one, the _E. coli_ is really so different they should never go with the sera. Is it possible there is some shift or error in the matching of the sample names/labels and tree nodes? It does converge to a more expected results, but this could theoretically happen even if there is a bug (the effect of which is diluted with more correctly aligned comparisons and labels.

**Comment by magnuspalmblad** [comment]
See [this screenshot](https://drive.google.com/file/d/1CA-PkjgkzgOu0YG5v8aHdbEhOcUOo71g/view?usp=sharing). Sample S01539 is a chimpanzee serum, and should not be grouped with S01540, which is _E. coli_. It looks like there is often one sample/label that is misplaced (until the very end). Does that help identify the bug?

**Comment by magnuspalmblad** [comment]
In the final tree displayed, the S01539 is missing from the tree, though both datasets are in the MEGA file.

**Comment by 524D** [comment]
The reason for this is that the compareMS2_to_distance_matrix executable does not handle the situation where the "sample-to-species" file contains more entries than have have been processed. In that case, the list at the start of the Mega file seems to contain all species/filenames. 
Probably related is that under the same conditions, compareMS2_to_distance_matrix sometimes causes output where the distance matrix contains empty lines, causing the GUI to draw an incomplete tree.
This can be solved by always offering compareMS2_to_distance_matrix a "sample-to-species" file that exactly matches the available results, or by making compareMS2_to_distance_matrix more tolerant. The first solution seems like a kludge, because it requires the GUI to parse/process/filter the "sample-to-species" file that it otherwise has no business with. Therefore, I will try to add the change to compareMS2_to_distance_matrix.

**Comment by 524D** [comment]
This should work correctly with version 0.0.3. There are still two  _E. coli_ samples that are grouped with the sera (filenames ending with _1152 and _1153). Inspecting the output of the compareMS2 command line executable shows that indeed the `fraction_gt_cutoff` is larger between those files and the nearest serum file (filename ending with _0134) than compared to the other  _E. coli_ files. Maybe those files contain contaminations.
